import { serve } from '../lib/serve.mjs';
import { launch } from '../lib/browser.mjs';
const { srv, url } = await serve();
const b = await launch();
const p = await b.newPage();
await p.setViewport({ width: 1440, height: 810 });
const errs = [];
p.on('console', m => { if (m.type() === 'error' || /engine|audio|player/i.test(m.text())) errs.push(m.type() + ': ' + m.text()); });
p.on('pageerror', e => errs.push('EXC ' + e.message));
await p.goto(`${url}/index.html?t=138`, { waitUntil: 'load' });
await p.evaluate(() => window.__ready);
await p.screenshot({ path: 'tools/verify/out/player-gate.jpg', type: 'jpeg', quality: 85 });
await p.click('.gate-play');
await new Promise(r => setTimeout(r, 4000));
await p.keyboard.press('KeyI');
await p.mouse.move(700, 700);
await new Promise(r => setTimeout(r, 600));
const st = await p.evaluate(() => ({ ctx: document.querySelector('.debug').textContent, time: document.querySelector('.time').textContent, playing: document.body.classList.contains('playing') }));
await p.screenshot({ path: 'tools/verify/out/player-playing.jpg', type: 'jpeg', quality: 85 });
await p.keyboard.press('BracketRight');
await new Promise(r => setTimeout(r, 1500));
const st2 = await p.evaluate(() => document.querySelector('.time').textContent);
console.log(JSON.stringify(st, null, 1), '\nafter ]:', st2, '\nerrors:', errs.slice(0, 10));
await b.close(); srv.close();
