// Regenerates src/assets/prompt.js from src/assets/prompt.txt so timeline.js can import the
// exact prompt text synchronously in both the browser and Node.
import fs from 'node:fs';
const root = new URL('..', import.meta.url).pathname;
const text = fs.readFileSync(root + 'src/assets/prompt.txt', 'utf8').replace(/\s+$/, '');
fs.writeFileSync(root + 'src/assets/prompt.js',
  '// GENERATED by tools/build-prompt.mjs from prompt.txt: do not edit by hand.\n' +
  'export const PROMPT = ' + JSON.stringify(text) + ';\n');
console.log('prompt.js:', text.length, 'chars');
